/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import User.AdminExecutive;
import User.BuildingManager;
import User.ManagerTeamStructureMgmt;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class AdminAddNewEmp extends javax.swing.JFrame {

    /**
     * Creates new form newResidentTenant
     */
    public AdminAddNewEmp() {
        initComponents();
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mgmtLoginPageLabel4 = new javax.swing.JLabel();
        fullNameLabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        phoneTF = new javax.swing.JTextField();
        fullNameTF = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        positionLabel = new javax.swing.JLabel();
        positionOption = new javax.swing.JComboBox<>();
        icLabel = new javax.swing.JLabel();
        icTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mgmtLoginPageLabel4.setFont(new java.awt.Font("Goudy Old Style", 3, 36)); // NOI18N
        mgmtLoginPageLabel4.setText("Add Employee Page");

        fullNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        fullNameLabel.setText("Full Name");

        PhoneLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        PhoneLabel.setText("Phone");

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        positionLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        positionLabel.setText("Position");

        positionOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Technician", "Cleaner", "Security Guard" }));
        positionOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionOptionActionPerformed(evt);
            }
        });

        icLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        icLabel.setText("IC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(mgmtLoginPageLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fullNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(fullNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(positionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(icLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(icTF, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(positionOption, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addGap(14, 14, 14)
                .addComponent(mgmtLoginPageLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(positionOption, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(positionLabel))
                .addGap(41, 41, 41)
                .addComponent(addBtn)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        AdminExecutive admin = new AdminExecutive(null,null);
        
        String name = fullNameTF.getText();
        String ic = icTF.getText();
        String phoneNum = phoneTF.getText();
        
        if (fullNameTF.getText().isEmpty() || icTF.getText().isEmpty() ||
               phoneTF.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please insert all the required information!", "Error", JOptionPane.ERROR_MESSAGE);
        
        }else {
            String positionOptionStr = (String) positionOption.getSelectedItem();
            if (positionOptionStr.equals("Technician")){
                String file = "database\\employee.txt";
                
                int count = 0;
                try {
                    File filePath = new File("database\\employee.txt");
                    Scanner sc = new Scanner(filePath);
                    
                    while(sc.hasNextLine()) {
                        sc.nextLine();
                        count++;
                    }
                    String i = Integer.toString(count);
                    sc.close();
                } catch (Exception e) {
                    e.getStackTrace();
                }
                String id = "E" + count;
                if(admin.addEmp(id, name, ic, phoneNum, "technician")){
                    JOptionPane.showMessageDialog(this, "Technican added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    fullNameTF.setText("");
                    icTF.setText("");
                    phoneTF.setText("");
                    
                }else {
                    JOptionPane.showMessageDialog(this, "Failed to add new technician.", "Error", JOptionPane.ERROR_MESSAGE);
                    fullNameTF.setText("");
                    icTF.setText("");
                    phoneTF.setText("");
                }
            } else if (positionOptionStr.equals("Cleaner")){
                String file = "database\\employee.txt";
                int count = 0;
                try {
                    File filePath = new File("database\\employee.txt");
                    Scanner sc = new Scanner(filePath);
                    
                    
                    while(sc.hasNextLine()) {
                        sc.nextLine();
                        count++;
                    }
                    String i = Integer.toString(count);
                    sc.close();
                } catch (Exception e) {
                    e.getStackTrace();
                }
                String id = "E" + count;
                if(admin.addEmp(id, name, ic, phoneNum, "cleaner")){
                    JOptionPane.showMessageDialog(this, "Cleaner added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    fullNameTF.setText("");
                    icTF.setText("");
                    phoneTF.setText("");
                    
                }else {
                    JOptionPane.showMessageDialog(this, "Failed to add new cleaner.", "Error", JOptionPane.ERROR_MESSAGE);
                    fullNameTF.setText("");
                    icTF.setText("");
                    phoneTF.setText("");
                }
                
        } else if (positionOptionStr.equals("Security Guard")){
            String file = "database\\employee.txt";
                int count = 0;
                try {
                    File filePath = new File("database\\employee.txt");
                    Scanner sc = new Scanner(filePath);
                    
                    
                    while(sc.hasNextLine()) {
                        sc.nextLine();
                        count++;
                    }
                    String i = Integer.toString(count);
                    sc.close();
                } catch (Exception e) {
                    e.getStackTrace();
                }
                String id = "E" + count;
                if(admin.addEmp(id, name, ic, phoneNum, "security guard")){
                    JOptionPane.showMessageDialog(this, "Security guard added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    fullNameTF.setText("");
                    icTF.setText("");
                    phoneTF.setText("");
                    
                }else {
                    JOptionPane.showMessageDialog(this, "Failed to add new security guard.", "Error", JOptionPane.ERROR_MESSAGE);
                    fullNameTF.setText("");
                    icTF.setText("");
                    phoneTF.setText("");
                }
        }
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        new AdminCleanerManagement().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void positionOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionOptionActionPerformed
        //         searchOption = new JComboBox<>(new String[]{"Username", "Unit No"});
        //         String selected = (String) searchOption.getSelectedItem();
    }//GEN-LAST:event_positionOptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddNewEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddNewEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddNewEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddNewEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AdminAddNewEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JTextField fullNameTF;
    private javax.swing.JLabel icLabel;
    private javax.swing.JTextField icTF;
    private javax.swing.JLabel mgmtLoginPageLabel4;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JComboBox<String> positionOption;
    // End of variables declaration//GEN-END:variables
}
