/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import User.Facility;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author hoong
 */
public class GymRoomManagement extends javax.swing.JFrame {
    public String fileLoc = "database\\gymequipment.txt";
    /**
     * Creates new form GymRoomManagement
     */
    public GymRoomManagement() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        try {
//            String filePath ="database\\gymequipment.txt";
            File file = new File(fileLoc);
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split(":");
            DefaultTableModel model = (DefaultTableModel)GymEquipmentTable.getModel();
            model.setColumnIdentifiers(columnsName);
            Object[] tableLines = br.lines().toArray();
            
            for (int i = 0; i < tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(":");
                model.addRow(dataRow);
            }
        } catch (IOException ex) {
            Logger.getLogger(GymRoomManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GymEquipmentTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        EquipmentLabel = new javax.swing.JLabel();
        EquipmentTF = new javax.swing.JTextField();
        QuantityTF = new javax.swing.JTextField();
        updateGymBtn = new javax.swing.JButton();
        deleteGymBtn = new javax.swing.JButton();
        addGymBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 3, 36)); // NOI18N
        jLabel1.setText("Gym Room Equipment List");

        GymEquipmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        GymEquipmentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GymEquipmentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(GymEquipmentTable);

        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 3, 36)); // NOI18N
        jLabel2.setText("Quantity");

        EquipmentLabel.setFont(new java.awt.Font("Goudy Old Style", 3, 36)); // NOI18N
        EquipmentLabel.setText("Equipment");

        EquipmentTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EquipmentTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipmentTFActionPerformed(evt);
            }
        });

        QuantityTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        updateGymBtn.setText("Update");
        updateGymBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateGymBtnActionPerformed(evt);
            }
        });

        deleteGymBtn.setText("Delete");
        deleteGymBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteGymBtnActionPerformed(evt);
            }
        });

        addGymBtn.setText("Add Product");
        addGymBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGymBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(EquipmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EquipmentTF, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(updateGymBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(QuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deleteGymBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(addGymBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EquipmentTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EquipmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateGymBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteGymBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(addGymBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EquipmentTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipmentTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipmentTFActionPerformed

    private void GymEquipmentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GymEquipmentTableMouseClicked
        // TODO add your handling code here:
        int i = GymEquipmentTable.getSelectedRow();
        TableModel model = GymEquipmentTable.getModel();
        EquipmentTF.setText(model.getValueAt(i,0).toString());
        QuantityTF.setText(model.getValueAt(i,1).toString());
    }//GEN-LAST:event_GymEquipmentTableMouseClicked

    private void updateGymBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateGymBtnActionPerformed
        // TODO add your handling code here:
        if (EquipmentTF.getText().isEmpty() || QuantityTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Equipment Name and Quantity.");
            return;
        }
        String newEquipment = EquipmentTF.getText();
        int newQuantity = Integer.parseInt(QuantityTF.getText());
        Facility eq = new Facility();
        DefaultTableModel model = (DefaultTableModel)GymEquipmentTable.getModel();
        if (eq.editEquipment(newEquipment, newQuantity, fileLoc)){
            JOptionPane.showMessageDialog(this,  newEquipment + " Successfully Updated");
        } else {
            JOptionPane.showMessageDialog(this, newEquipment +  " Does Not Exist, Please Use Add Product Button Instead");
        }
        eq.refreshTable(GymEquipmentTable, model, fileLoc);
        clear();
    }//GEN-LAST:event_updateGymBtnActionPerformed

    private void deleteGymBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGymBtnActionPerformed
        // TODO add your handling code here:
        if (EquipmentTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Equipment Name.");
            return;
        }
        String newEquipment = EquipmentTF.getText();
        Facility eq = new Facility();
        DefaultTableModel model = (DefaultTableModel)GymEquipmentTable.getModel();
        
        if (eq.deleteEquipment(newEquipment, fileLoc)){
            JOptionPane.showMessageDialog(this,  newEquipment + " Successfully Deleted");
        } else {
            JOptionPane.showMessageDialog(this, newEquipment +  " Does Not Exist, Delete Failed");
        }
        eq.refreshTable(GymEquipmentTable, model, fileLoc);
        clear();
    }//GEN-LAST:event_deleteGymBtnActionPerformed

    private void addGymBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGymBtnActionPerformed
        // TODO add your handling code here:
        if (EquipmentTF.getText().isEmpty() || QuantityTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Equipment Name and Quantity.");
            return;
        }
        String newEquipment = EquipmentTF.getText();
        int newQuantity = Integer.parseInt(QuantityTF.getText());
        Facility eq = new Facility();
        DefaultTableModel model = (DefaultTableModel)GymEquipmentTable.getModel();
        if (eq.addEquipment(newEquipment, newQuantity, fileLoc)){
            JOptionPane.showMessageDialog(this,  newEquipment + " Successfully Added");
        } else {
            JOptionPane.showMessageDialog(this, newEquipment +  " Name Already Exist");
        }
        eq.refreshTable(GymEquipmentTable, model, fileLoc);
        clear();
    }//GEN-LAST:event_addGymBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new AdminFacilityManagement().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    public void clear() {
        EquipmentTF.setText("");
        QuantityTF.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GymRoomManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GymRoomManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GymRoomManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GymRoomManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GymRoomManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EquipmentLabel;
    private javax.swing.JTextField EquipmentTF;
    private javax.swing.JTable GymEquipmentTable;
    private javax.swing.JTextField QuantityTF;
    private javax.swing.JButton addGymBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteGymBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateGymBtn;
    // End of variables declaration//GEN-END:variables
}
