/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import User.AccountExecutive;
import User.AdminExecutive;
import User.BuildingExecutive;
import User.BuildingManager;
import User.User;

/**
 *
 * @author Asus
 */
public class LoginMgmt extends javax.swing.JFrame {

    /**
     * Creates new form LoginMgmt
     */
    public LoginMgmt() {
        initComponents();
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mgmtLoginPageLabel2 = new javax.swing.JLabel();
        mgmtUsernameLabel = new javax.swing.JLabel();
        mgmtPasswordLabel = new javax.swing.JLabel();
        mgmtUsernameTxtField = new javax.swing.JTextField();
        mgmtPassTxtField = new javax.swing.JTextField();
        mgmtLoginBtn = new javax.swing.JButton();
        mgmtLoginPageLabel = new javax.swing.JLabel();
        mgmtLoginPageLabel3 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        mgmtLoginPageLabel2.setFont(new java.awt.Font("Goudy Old Style", 3, 36)); // NOI18N
        mgmtLoginPageLabel2.setText("Login Page");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mgmtUsernameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mgmtUsernameLabel.setText("Username:");

        mgmtPasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mgmtPasswordLabel.setText("Password:");

        mgmtUsernameTxtField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mgmtUsernameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mgmtUsernameTxtFieldActionPerformed(evt);
            }
        });

        mgmtPassTxtField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mgmtPassTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mgmtPassTxtFieldActionPerformed(evt);
            }
        });

        mgmtLoginBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mgmtLoginBtn.setText("Login");
        mgmtLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mgmtLoginBtnActionPerformed(evt);
            }
        });

        mgmtLoginPageLabel.setFont(new java.awt.Font("Goudy Old Style", 3, 36)); // NOI18N
        mgmtLoginPageLabel.setText("Management Login Page");

        mgmtLoginPageLabel3.setFont(new java.awt.Font("Goudy Old Style", 3, 36)); // NOI18N
        mgmtLoginPageLabel3.setText("Parkhill Residence");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mgmtPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mgmtUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mgmtPassTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(mgmtUsernameTxtField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(mgmtLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(mgmtLoginPageLabel3)
                                .addGap(49, 49, 49))
                            .addComponent(mgmtLoginPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mgmtLoginPageLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mgmtLoginPageLabel)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mgmtUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mgmtUsernameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mgmtPasswordLabel)
                    .addComponent(mgmtPassTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(mgmtLoginBtn)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mgmtUsernameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mgmtUsernameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mgmtUsernameTxtFieldActionPerformed

    private void mgmtPassTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mgmtPassTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mgmtPassTxtFieldActionPerformed

    private void mgmtLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mgmtLoginBtnActionPerformed
        login();
    }//GEN-LAST:event_mgmtLoginBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        new MainMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginMgmt().setVisible(true);
            }
        });
    }
    
    public void login(){
        BuildingManager buildingManager = new BuildingManager("manager", "manager123");
        AccountExecutive accountExe = new AccountExecutive("account", "account123");
        AdminExecutive admin = new AdminExecutive("admin", "admin123");
        BuildingExecutive buildingExe = new BuildingExecutive("building", "building123");
        
        // check user role
        if (mgmtUsernameTxtField.getText().equals("manager")){
            login(buildingManager, "manager", "manager123");
        } else if (mgmtUsernameTxtField.getText().equals("account")){
            login(accountExe, "account","account123");
        } else if (mgmtUsernameTxtField.getText().equals("admin")){
            login(admin, "admin","admin123");
        } else if (mgmtUsernameTxtField.getText().equals("building")){
            login(buildingExe, "building", "building123");
        }else {
            JOptionPane.showMessageDialog(this,
                    "Login Failed! \nIncorrect Username or Password.",
                    "Error Message",
                    JOptionPane.ERROR_MESSAGE);
            mgmtUsernameTxtField.setText("");
            mgmtPassTxtField.setText("");
        }
    }
    
    public void login(User user, String username, String password){
        String userName;
        String pass;
        
        // get the username & password typed from text field
        userName = mgmtUsernameTxtField.getText();
        pass = mgmtPassTxtField.getText();
        
        // check password
        if (user.login(userName,pass)){
            JOptionPane.showMessageDialog(this, "Login Successful.");
            this.setVisible(false);
            
            // logs the user in and calls the appropriate method based on the user role
            if(user instanceof BuildingManager){
                ((BuildingManager) user).buidingManagerMenu();
            }else if (user instanceof AccountExecutive){
                ((AccountExecutive) user).accountExeMenu();
            }else if (user instanceof AdminExecutive){
                ((AdminExecutive) user).adminMenu();
            }else if (user instanceof BuildingExecutive){
                ((BuildingExecutive) user).buildingExeMenu();
            }
            
        } else {
            JOptionPane.showMessageDialog(this,
                    "Login Failed! \nIncorrect Username or Password.",
                    "Error Message",
                    JOptionPane.ERROR_MESSAGE);
            mgmtUsernameTxtField.setText("");
            mgmtPassTxtField.setText("");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton mgmtLoginBtn;
    private javax.swing.JLabel mgmtLoginPageLabel;
    private javax.swing.JLabel mgmtLoginPageLabel2;
    private javax.swing.JLabel mgmtLoginPageLabel3;
    private javax.swing.JTextField mgmtPassTxtField;
    private javax.swing.JLabel mgmtPasswordLabel;
    private javax.swing.JLabel mgmtUsernameLabel;
    private javax.swing.JTextField mgmtUsernameTxtField;
    // End of variables declaration//GEN-END:variables
}
