/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import User.AccountExecutive;
import User.AdminExecutive;
import User.BuildingExecutive;
import User.BuildingManager;
import User.User;

/**
 *
 * @author Asus
 */
public class LoginMgmt extends javax.swing.JFrame {

    /**
     * Creates new form LoginMgmt
     */
    public LoginMgmt() {
        initComponents();
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountExeUsernameLabel = new javax.swing.JLabel();
        accountExePasswordLabel = new javax.swing.JLabel();
        usernameTxtField = new javax.swing.JTextField();
        passTxtField = new javax.swing.JTextField();
        adminLoginBtn = new javax.swing.JButton();
        mgmtLoginPageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        accountExeUsernameLabel.setText("Username:");

        accountExePasswordLabel.setText("Password:");

        usernameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtFieldActionPerformed(evt);
            }
        });

        passTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTxtFieldActionPerformed(evt);
            }
        });

        adminLoginBtn.setText("Login");
        adminLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginBtnActionPerformed(evt);
            }
        });

        mgmtLoginPageLabel.setFont(new java.awt.Font("Goudy Old Style", 3, 36)); // NOI18N
        mgmtLoginPageLabel.setText("Management Login Page");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(accountExePasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(passTxtField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(accountExeUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(usernameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(adminLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(mgmtLoginPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(mgmtLoginPageLabel)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountExeUsernameLabel)
                    .addComponent(usernameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountExePasswordLabel)
                    .addComponent(passTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(adminLoginBtn)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTxtFieldActionPerformed

    private void passTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTxtFieldActionPerformed

    private void adminLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginBtnActionPerformed
        login();
    }//GEN-LAST:event_adminLoginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginMgmt().setVisible(true);
            }
        });
    }
    
    public void login(){
        BuildingManager buildingManager = new BuildingManager("manager", "manager123");
        AccountExecutive accountExe = new AccountExecutive("account", "account123");
        AdminExecutive admin = new AdminExecutive("admin", "admin123");
        BuildingExecutive buildingExe = new BuildingExecutive("building", "building123");
        
        // check user role
        if (usernameTxtField.getText().equals("manager")){
            login(buildingManager, "manager", "manager123");
        } else if (usernameTxtField.getText().equals("account")){
            login(accountExe, "account","account123");
        } else if (usernameTxtField.getText().equals("admin")){
            login(admin, "admin","admin123");
        } else if (usernameTxtField.getText().equals("building")){
            login(buildingExe, "building", "building123");
        }else {
            JOptionPane.showMessageDialog(this,
                    "Login Failed! \nIncorrect Username or Password.",
                    "Error Message",
                    JOptionPane.ERROR_MESSAGE);
            usernameTxtField.setText("");
            passTxtField.setText("");
        }
    }
    
    public void login(User user, String username, String password){
        String userName;
        String pass;
        
        // get the username & password typed from text field
        userName = usernameTxtField.getText();
        pass = passTxtField.getText();
        
        // check password
        if (user.login(userName,pass)){
            JOptionPane.showMessageDialog(this, "Login Successful.");
            this.setVisible(false);
            
            // logs the user in and calls the appropriate method based on the user role
            if(user instanceof BuildingManager){
                ((BuildingManager) user).buidingManagerMenu();
            }else if (user instanceof AccountExecutive){
                ((AccountExecutive) user).accountExeMenu();
            }else if (user instanceof AdminExecutive){
                ((AdminExecutive) user).adminMenu();
            }else if (user instanceof BuildingExecutive){
                ((BuildingExecutive) user).buildingExeMenu();
            }
            
        } else {
            JOptionPane.showMessageDialog(this,
                    "Login Failed! \nIncorrect Username or Password.",
                    "Error Message",
                    JOptionPane.ERROR_MESSAGE);
            usernameTxtField.setText("");
            passTxtField.setText("");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountExePasswordLabel;
    private javax.swing.JLabel accountExeUsernameLabel;
    private javax.swing.JButton adminLoginBtn;
    private javax.swing.JLabel mgmtLoginPageLabel;
    private javax.swing.JTextField passTxtField;
    private javax.swing.JTextField usernameTxtField;
    // End of variables declaration//GEN-END:variables
}
