/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class ReceiptPage extends javax.swing.JFrame {

    /**
     * Creates new form Receipt
     */
    public ReceiptPage() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        
        CusName.setBackground(new java.awt.Color(0,0,0,1));
        unit.setBackground(new java.awt.Color(0,0,0,1));
        receiptTF.setBackground(new java.awt.Color(0,0,0,1));
        dateTF.setBackground(new java.awt.Color(0,0,0,1));
        unitTF.setBackground(new java.awt.Color(0,0,0,1));
        bankTF.setBackground(new java.awt.Color(0,0,0,1));
        issueByTF.setBackground(new java.awt.Color(0,0,0,1));
        
        
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing (WindowEvent e){
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        condoName = new javax.swing.JLabel();
        condoAddress = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        condoContact = new javax.swing.JLabel();
        Receipt = new javax.swing.JLabel();
        receiptTF = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        dateTF = new javax.swing.JTextField();
        unitNo = new javax.swing.JLabel();
        unitTF = new javax.swing.JTextField();
        unit1 = new javax.swing.JLabel();
        CusName = new javax.swing.JTextField();
        unit = new javax.swing.JTextField();
        jalan = new javax.swing.JLabel();
        taman = new javax.swing.JLabel();
        postcode = new javax.swing.JLabel();
        area = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chargesTable = new javax.swing.JTable();
        total = new javax.swing.JLabel();
        totalTF = new javax.swing.JTextField();
        paymentMode = new javax.swing.JLabel();
        bank = new javax.swing.JLabel();
        bankTF = new javax.swing.JTextField();
        issueBy = new javax.swing.JLabel();
        issueByTF = new javax.swing.JTextField();
        paymentModeTF = new javax.swing.JLabel();
        Note = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        condoName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        condoName.setText("Parkhill Residence");

        condoAddress.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        condoAddress.setText("No. 27, Jalan 3/88, Technology Park, 57000 Kuala Lumpur, WP Kuala Lumpur.");

        title.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        title.setText("Official Receipt");

        condoContact.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        condoContact.setText("Tel: 03-2257683    Email: mo.phmc2023@gmail.com");

        Receipt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Receipt.setText("Receipt No.:");

        receiptTF.setEditable(false);
        receiptTF.setBackground(new java.awt.Color(255, 255, 255));
        receiptTF.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        receiptTF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        receiptTF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        receiptTF.setFocusable(false);
        receiptTF.setOpaque(false);
        receiptTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptTFActionPerformed(evt);
            }
        });

        date.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        date.setText("Date: ");

        dateTF.setEditable(false);
        dateTF.setBackground(new java.awt.Color(255, 255, 255));
        dateTF.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dateTF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dateTF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dateTF.setFocusable(false);
        dateTF.setOpaque(false);
        dateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTFActionPerformed(evt);
            }
        });

        unitNo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        unitNo.setText("Unit No.:");

        unitTF.setEditable(false);
        unitTF.setBackground(new java.awt.Color(255, 255, 255));
        unitTF.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        unitTF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        unitTF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        unitTF.setFocusable(false);
        unitTF.setOpaque(false);
        unitTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitTFActionPerformed(evt);
            }
        });

        unit1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        unit1.setText("Received From: ");

        CusName.setEditable(false);
        CusName.setBackground(new java.awt.Color(255, 255, 255));
        CusName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CusName.setText("Low Jye Shan");
        CusName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CusName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CusName.setFocusable(false);
        CusName.setOpaque(false);
        CusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusNameActionPerformed(evt);
            }
        });

        unit.setEditable(false);
        unit.setBackground(new java.awt.Color(255, 255, 255));
        unit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        unit.setText("B-7-1, Parkhill Residence,");
        unit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        unit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        unit.setFocusable(false);
        unit.setOpaque(false);
        unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitActionPerformed(evt);
            }
        });

        jalan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jalan.setText("No. 27, Jalan 3/88,");

        taman.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        taman.setText("Technology Park,");

        postcode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        postcode.setText("57000 Kuala Lumpur,");

        area.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        area.setText("WP Kuala Lumpur.");

        chargesTable.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        chargesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Description", "Amount (RM)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        chargesTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(chargesTable);

        total.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        total.setText("Total Current Charges (RM)");

        totalTF.setEditable(false);
        totalTF.setBackground(new java.awt.Color(255, 255, 255));
        totalTF.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        totalTF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalTF.setText("12.00");
        totalTF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        totalTF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        totalTF.setFocusable(false);
        totalTF.setOpaque(false);
        totalTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTFActionPerformed(evt);
            }
        });

        paymentMode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        paymentMode.setText("Payment Mode:");

        bank.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bank.setText("Bank:");

        bankTF.setEditable(false);
        bankTF.setBackground(new java.awt.Color(255, 255, 255));
        bankTF.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bankTF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bankTF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bankTF.setFocusable(false);
        bankTF.setOpaque(false);
        bankTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankTFActionPerformed(evt);
            }
        });

        issueBy.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        issueBy.setText("Issued By:");

        issueByTF.setEditable(false);
        issueByTF.setBackground(new java.awt.Color(255, 255, 255));
        issueByTF.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        issueByTF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        issueByTF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        issueByTF.setFocusable(false);
        issueByTF.setOpaque(false);
        issueByTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueByTFActionPerformed(evt);
            }
        });

        paymentModeTF.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        paymentModeTF.setText("Online IBG");

        Note.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Note.setText("This is a computer generated document. No signature is required.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(condoContact)
                        .addGap(209, 209, 209))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(condoAddress))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(266, 266, 266)
                                .addComponent(condoName)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(total)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(unitNo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(unitTF)
                                        .addGap(187, 187, 187)
                                        .addComponent(Receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(unit1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jalan)
                                                    .addComponent(taman)
                                                    .addComponent(postcode)
                                                    .addComponent(area))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(unit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                                    .addComponent(CusName, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(receiptTF, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(dateTF)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(issueBy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(issueByTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bank, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bankTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(paymentMode)
                                        .addGap(18, 18, 18)
                                        .addComponent(paymentModeTF)))
                                .addGap(420, 420, 420)))))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Note)
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(condoName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(condoAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(condoContact)
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Receipt)
                    .addComponent(receiptTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitNo)
                    .addComponent(unitTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date)
                    .addComponent(unit1)
                    .addComponent(CusName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(unit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jalan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postcode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(area)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total)
                    .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentMode)
                    .addComponent(paymentModeTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bank)
                    .addComponent(bankTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issueBy)
                    .addComponent(issueByTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(Note)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void receiptTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiptTFActionPerformed

    private void dateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTFActionPerformed

    private void unitTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitTFActionPerformed

    private void CusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CusNameActionPerformed

    private void unitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitActionPerformed

    private void totalTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTFActionPerformed

    private void bankTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankTFActionPerformed

    private void issueByTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueByTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issueByTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceiptPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceiptPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceiptPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceiptPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceiptPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CusName;
    private javax.swing.JLabel Note;
    private javax.swing.JLabel Receipt;
    private javax.swing.JLabel area;
    private javax.swing.JLabel bank;
    private javax.swing.JTextField bankTF;
    private javax.swing.JTable chargesTable;
    private javax.swing.JLabel condoAddress;
    private javax.swing.JLabel condoContact;
    private javax.swing.JLabel condoName;
    private javax.swing.JLabel date;
    private javax.swing.JTextField dateTF;
    private javax.swing.JLabel issueBy;
    private javax.swing.JTextField issueByTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jalan;
    private javax.swing.JLabel paymentMode;
    private javax.swing.JLabel paymentModeTF;
    private javax.swing.JLabel postcode;
    private javax.swing.JTextField receiptTF;
    private javax.swing.JLabel taman;
    private javax.swing.JLabel title;
    private javax.swing.JLabel total;
    private javax.swing.JTextField totalTF;
    private javax.swing.JTextField unit;
    private javax.swing.JLabel unit1;
    private javax.swing.JLabel unitNo;
    private javax.swing.JTextField unitTF;
    // End of variables declaration//GEN-END:variables
}
