/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import User.Resident;
import User.Vendor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ResidentViewPayment extends getActiveUser {

    /**
     * Creates new form ResidentViewPayment
     */
    public ResidentViewPayment() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
//        setDefaultCloseOperation(ResidentViewPayment.DISPOSE_ON_CLOSE);
        
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing (WindowEvent e){
                dispose();
            }
        });
        
        setPaymentTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentHistory = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        paymentTable = new javax.swing.JTable();
        invoice1 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        paymentDate = new javax.swing.JLabel();
        bank = new javax.swing.JLabel();
        amount2 = new javax.swing.JLabel();
        amountTF2 = new javax.swing.JTextField();
        bankTF = new javax.swing.JTextField();
        dueTF1 = new javax.swing.JTextField();
        statusTF = new javax.swing.JTextField();
        invoiceTF1 = new javax.swing.JTextField();
        paymentDate1 = new javax.swing.JLabel();
        pymNo = new javax.swing.JTextField();
        bank1 = new javax.swing.JLabel();
        descTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paymentHistory.setFont(new java.awt.Font("Goudy Old Style", 3, 36)); // NOI18N
        paymentHistory.setText("Payment History");

        paymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice No.", "Payment Date", "Bank", "Description", "Amount (RM)", "Status", "Payment No."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        paymentTable.getTableHeader().setReorderingAllowed(false);
        paymentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paymentTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(paymentTable);

        invoice1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        invoice1.setText("Invoice No.");

        status.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        status.setText("Status");

        paymentDate.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        paymentDate.setText("Payment Date");

        bank.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        bank.setText("Bank");

        amount2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        amount2.setText("Amount (RM)");

        amountTF2.setEditable(false);

        bankTF.setEditable(false);

        dueTF1.setEditable(false);

        statusTF.setEditable(false);

        invoiceTF1.setEditable(false);

        paymentDate1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        paymentDate1.setText("Payment No.");

        pymNo.setEditable(false);

        bank1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        bank1.setText("Description");

        descTF.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(paymentHistory)
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(status, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bank)
                                .addComponent(invoice1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bank1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(descTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(statusTF, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                    .addComponent(bankTF, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                    .addComponent(invoiceTF1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(paymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(amount2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dueTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(amountTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(paymentDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pymNo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(paymentHistory)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoiceTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoice1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pymNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dueTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bankTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bank, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bank1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paymentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)paymentTable.getModel();
        String invNo = model.getValueAt(paymentTable.getSelectedRow(), 0).toString();
        String date = model.getValueAt(paymentTable.getSelectedRow(), 1).toString();
        String bank = model.getValueAt(paymentTable.getSelectedRow(), 2).toString();
        String desc = model.getValueAt(paymentTable.getSelectedRow(), 3).toString();
        String amt = model.getValueAt(paymentTable.getSelectedRow(), 4).toString();
        String status = model.getValueAt(paymentTable.getSelectedRow(), 5).toString();
        String pymId = model.getValueAt(paymentTable.getSelectedRow(), 6).toString();
        
        invoiceTF1.setText(invNo);
        dueTF1.setText(date);
        bankTF.setText(bank);
        amountTF2.setText(amt);
        statusTF.setText(status);
        pymNo.setText(pymId);
        descTF.setText(desc);
    }//GEN-LAST:event_paymentTableMouseClicked

    @Override
    public String[] getActiveUser(){
        String filePath = "database\\activeUser.txt";
        try{
            BufferedReader br = new BufferedReader(new FileReader(filePath));
            String line = br.readLine();
            String[] activeUser = line.split(",");           
            br.close();
            return activeUser;
        }catch(IOException e){
            System.out.println("Input Output Exception Occurred" + e);
            return null;
        }catch(Exception e) {
            System.out.println("Exception " + e);
            return null;
        }
    }
    
    private void setPaymentTable() {
        
        String currentUser = "";
        
        String filePath = "database\\payment.txt";
        String tempFile = "database\\tempActiveUserPayment.txt";
        String typeFile = "database\\userType.txt";
        try {
            BufferedReader bt = new BufferedReader(new FileReader(typeFile));
            String type = bt.readLine();
            if (type.equals("resident")){
                Resident res = new Resident(getActiveUser()[0], getActiveUser()[1]);
                currentUser = res.getFullName();
            } else if (type.equals("vendor")){
                Vendor ven = new Vendor(getActiveUser()[0], getActiveUser()[1]);
                currentUser = ven.getFullName();
            }
            bt.close();
            
            if (currentUser != ""){
                BufferedReader br = new BufferedReader(new FileReader(filePath));
                BufferedWriter bw = new BufferedWriter(new FileWriter(tempFile));
                String line;
                while ((line = br.readLine()) != null) {
                    String[] pymInfo = line.split(":");
                    String user = pymInfo[3];

                    if (user.equals(currentUser)){
                        bw.write(pymInfo[0] + ":" + pymInfo[1] + ":" + pymInfo[4] 
                                + ":" + pymInfo[5] + ":" + pymInfo[6] + ":" + 
                                pymInfo[8] + ":" + pymInfo[9] + "\n");

                    }
                }
                br.close();
                bw.close();

                BufferedReader br2 = new BufferedReader(new FileReader(tempFile));
                DefaultTableModel pymTable = (DefaultTableModel)paymentTable.getModel();
                Object[] record = br2.lines().toArray();
                for (int i = 0; i < record.length; i++){
                    String line2 = record[i].toString().trim();
                    String[] recInfo = line2.split(":");
                    pymTable.addRow(recInfo);
                }
                br2.close();
                new File(tempFile).delete();
            }
                    
        } catch (IOException ex) {
            System.out.println("Exception occur: " + ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResidentViewPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResidentViewPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResidentViewPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResidentViewPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResidentViewPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount2;
    private javax.swing.JTextField amountTF2;
    private javax.swing.JLabel bank;
    private javax.swing.JLabel bank1;
    private javax.swing.JTextField bankTF;
    private javax.swing.JTextField descTF;
    private javax.swing.JTextField dueTF1;
    private javax.swing.JLabel invoice1;
    private javax.swing.JTextField invoiceTF1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel paymentDate;
    private javax.swing.JLabel paymentDate1;
    private javax.swing.JLabel paymentHistory;
    private javax.swing.JTable paymentTable;
    private javax.swing.JTextField pymNo;
    private javax.swing.JLabel status;
    private javax.swing.JTextField statusTF;
    // End of variables declaration//GEN-END:variables
}
